import type { Metadata } from "next";
import { Inter, Poppins, Newsreader } from "@next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500","600", "700"], variable:'--font-poppins' });
const newsreader = Newsreader({ subsets: ["latin"], weight: ["400", "500", "700"], variable: '--font-newsreader' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${poppins.className} ${newsreader.className}`}>
      {/* <Layout>{children}</Layout> */}
      {children}
      </body>
    </html>
  );
}
 